services:
  - type: web
    name: ielts-api
    env: node
    rootDir: ielts-api
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://nextband.site
      - key: DATABASE_URL
        value: postgresql://postgres.gzpdlqxjggyxlkeatvvf:anhxtanhmat1@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=10&pool_timeout=20
      - key: JWT_SECRET
        value: jH3FrM+AfqdenAVbqkTviqvCkfZGUl9QKunFk4TCVlDpHWMgTQnJvYpXlNTk0Fr/
      - key: SUPABASE_URL
        value: https://gzpdlqxjggyxlkeatvvf.supabase.co
