services:
  - type: web
    name: ielts-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://nextband.site
