import { PrismaClient } from "@prisma/client";
import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";
import * as crypto from "crypto";

const prisma = new PrismaClient();

async function main() {
  console.log("================================================================================");
  console.log("             PHASE 2: RECONCILING PRISMA MIGRATION BASELINE (POSTGRESQL)        ");
  console.log("================================================================================\n");

  const prismaDir = path.resolve("d:/handover/ielts/ielts-api/prisma");
  const migrationsDir = path.join(prismaDir, "migrations");
  const legacyDir = path.join(prismaDir, "legacy_mysql_migrations");
  const baselineMigrationName = "20260821000000_init_postgresql";
  const baselineDir = path.join(migrationsDir, baselineMigrationName);

  // 1. Ensure legacy archive directory exists and move old migrations
  if (!fs.existsSync(legacyDir)) {
    fs.mkdirSync(legacyDir, { recursive: true });
  }

  const existingEntries = fs.readdirSync(migrationsDir);
  for (const entry of existingEntries) {
    if (entry !== "migration_lock.toml" && !entry.includes("postgresql")) {
      const src = path.join(migrationsDir, entry);
      const dest = path.join(legacyDir, entry);
      if (fs.existsSync(src)) {
        if (fs.existsSync(dest)) {
          fs.rmSync(dest, { recursive: true, force: true });
        }
        fs.renameSync(src, dest);
        console.log(`  - Archived legacy MySQL migration: ${entry}`);
      }
    }
  }

  // 2. Generate canonical PostgreSQL migration DDL
  if (!fs.existsSync(baselineDir)) {
    fs.mkdirSync(baselineDir, { recursive: true });
  }

  console.log(">>> Generating canonical PostgreSQL baseline migration SQL from schema.prisma...");
  const ddl = execSync("npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script", {
    cwd: path.resolve("d:/handover/ielts/ielts-api"),
    encoding: "utf-8",
  });

  const baselineSqlPath = path.join(baselineDir, "migration.sql");
  fs.writeFileSync(baselineSqlPath, ddl, "utf-8");
  console.log(`✓ Saved canonical PostgreSQL baseline: ${baselineSqlPath}`);

  // 3. Write migration_lock.toml for postgresql
  const lockContent = `# Please do not edit this file manually\n# It should be added in your version-control system (i.e. Git)\nprovider = "postgresql"\n`;
  fs.writeFileSync(path.join(migrationsDir, "migration_lock.toml"), lockContent, "utf-8");
  console.log("✓ Updated migration_lock.toml to provider = 'postgresql'");

  // 4. Calculate checksum for baseline migration
  const checksum = crypto.createHash("sha256").update(ddl).digest("hex");

  // 5. Initialize _prisma_migrations in PostgreSQL Supabase if not exists
  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
      "id"                    VARCHAR(36) PRIMARY KEY NOT NULL,
      "checksum"              VARCHAR(64) NOT NULL,
      "finished_at"           TIMESTAMPTZ,
      "migration_name"        VARCHAR(255) NOT NULL,
      "logs"                  TEXT,
      "rolled_back_at"        TIMESTAMPTZ,
      "started_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
      "applied_steps_count"   INTEGER NOT NULL DEFAULT 0
    );
  `);

  // 6. Record baseline migration as applied (since physical DB already has tables)
  const migrationId = crypto.randomUUID();
  await prisma.$executeRawUnsafe(`
    INSERT INTO "_prisma_migrations" (
      "id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count"
    ) VALUES (
      '${migrationId}',
      '${checksum}',
      now(),
      '${baselineMigrationName}',
      NULL,
      NULL,
      now(),
      1
    ) ON CONFLICT ("id") DO NOTHING;
  `);

  console.log(`✓ Marked baseline '${baselineMigrationName}' as applied in physical PostgreSQL ledger.`);

  console.log("\n================================================================================");
  console.log("       ✅ PRISMA MIGRATION RECONCILIATION COMPLETED SUCCESSFULLY                ");
  console.log("================================================================================");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
