import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export const CANDIDATE_SPEAKING_TAGS = [
  // ==========================================
  // 1. PRONUNCIATION (PR)
  // ==========================================
  {
    id: "PR_OMIT_FINAL_CONSONANT",
    criterion: "PR",
    polarity: "ISSUE",
    labelVi: "Nuốt âm đuôi (/s/, /t/, /d/, /ed/)",
    descriptionVi: "Bỏ quên hoặc không bật rõ phụ âm kết thúc từ đơn lẻ.",
    inclusionRule: "Gắn khi người học nói mất âm đuôi ở các từ cơ bản (VD: 'like' nói thành 'lai', 'past' nói thành 'pa').",
    exclusionRule: "Không gắn nếu thí sinh chỉ bỏ âm /s/ ở danh từ số nhiều nhưng các từ khác phát âm đuôi đầy đủ (khi đó ưu tiên GRA_MISSING_ARTICLES_PLURALS).",
    displayOrder: 1,
    version: "1.0",
  },
  {
    id: "PR_CHOPPY_NO_LINKING",
    criterion: "PR",
    polarity: "ISSUE",
    labelVi: "Nói từng từ rời rạc / Thiếu nối âm",
    descriptionVi: "Phát âm giật cục từng từ đơn lẻ, thiếu sự liên kết âm giữa phụ âm và nguyên âm.",
    inclusionRule: "Gắn khi bài nói có nhịp điệu ngắt quãng giữa các từ, không có hiện tượng linking sounds tự nhiên.",
    exclusionRule: "Không gắn nếu sự ngắt quãng bắt nguồn từ việc ngập ngừng tìm từ vựng (khi đó dùng FC_SEARCHING_PAUSE_LONG).",
    displayOrder: 2,
    version: "1.0",
  },
  {
    id: "PR_FLAT_INTONATION",
    criterion: "PR",
    polarity: "ISSUE",
    labelVi: "Ngữ điệu đều đều / Đi ngang",
    descriptionVi: "Giọng đọc đều như trả bài, thiếu cao độ lên/xuống tự nhiên ở mệnh đề và câu.",
    inclusionRule: "Gắn khi giọng nói phẳng lì, không có ngữ điệu lên ở vế mở hoặc xuống giọng ở cuối câu trần thuật.",
    exclusionRule: "Không gắn nếu thí sinh có ngữ điệu nhưng nói chậm do thiếu tự tin.",
    displayOrder: 3,
    version: "1.0",
  },
  {
    id: "PR_INCORRECT_WORD_STRESS",
    criterion: "PR",
    polarity: "ISSUE",
    labelVi: "Nhấn sai trọng âm từ",
    descriptionVi: "Đặt trọng âm sai âm tiết ở các từ đa âm tiết, gây khó hiểu cho người nghe.",
    inclusionRule: "Gắn khi thí sinh nhấn sai âm tiết chính của từ từ 2 âm tiết trở lên (VD: 'develop', 'comfortable').",
    exclusionRule: "Không gắn cho lỗi nhấn sai nhịp điệu của cả câu (khi đó dùng PR_FLAT_INTONATION).",
    displayOrder: 4,
    version: "1.0",
  },
  {
    id: "PR_CONSONANT_CLUSTER_DROP",
    criterion: "PR",
    polarity: "ISSUE",
    labelVi: "Rớt âm trong phụ âm kép (st, sp, tr, /θ/)",
    descriptionVi: "Nuốt bớt âm trong các tổ hợp phụ âm khó hoặc nhầm lẫn âm vô thanh/hữu thanh.",
    inclusionRule: "Gắn khi thí sinh gặp khó khăn với các cụm phụ âm đầu/giữa (street -> treet, speak -> peak, think -> tink).",
    exclusionRule: "Không gắn cho lỗi rớt âm cuối đơn lẻ (dùng PR_OMIT_FINAL_CONSONANT).",
    displayOrder: 5,
    version: "1.0",
  },
  {
    id: "PR_CLEAR_FINAL_CONSONANTS",
    criterion: "PR",
    polarity: "STRENGTH",
    labelVi: "Bật âm đuôi rõ ràng và chính xác",
    descriptionVi: "Phát âm tròn trịa, rõ ràng các âm đuôi /s/, /z/, /t/, /d/, /ed/.",
    inclusionRule: "Gắn khi thí sinh bật âm đuôi nhất quán, tự nhiên xuyên suốt các câu trả lời.",
    exclusionRule: "Không gắn nếu chỉ bật được 1-2 từ nhưng phần lớn bài nói vẫn nuốt âm đuôi.",
    displayOrder: 6,
    version: "1.0",
  },
  {
    id: "PR_SMOOTH_CONNECTED_SPEECH",
    criterion: "PR",
    polarity: "STRENGTH",
    labelVi: "Nối âm và lướt âm tự nhiên",
    descriptionVi: "Có hiện tượng nối phụ âm sang nguyên âm mượt mà, lướt âm tự nhiên như người bản xứ.",
    inclusionRule: "Gắn khi thí sinh sử dụng connected speech linh hoạt (VD: 'pick it up', 'as a matter of fact').",
    exclusionRule: "Không gắn nếu chỉ nói nhanh nhưng các từ va vào nhau gây nhòe âm.",
    displayOrder: 7,
    version: "1.0",
  },
  {
    id: "PR_NATURAL_SENTENCE_STRESS",
    criterion: "PR",
    polarity: "STRENGTH",
    labelVi: "Nhấn nhá nhịp điệu câu rất tự nhiên",
    descriptionVi: "Nhấn đúng từ khóa nội dung (Content words), hạ nhẹ từ chức năng, tạo nhịp điệu chuẩn.",
    inclusionRule: "Gắn khi bài nói có độ tương phản nhịp điệu rõ ràng, thể hiện tốt cảm xúc và điểm nhấn ý nghĩa.",
    exclusionRule: "Không gắn nếu thí sinh chỉ nhấn âm đều đều theo công thức cơ học.",
    displayOrder: 8,
    version: "1.0",
  },

  // ==========================================
  // 2. FLUENCY & COHERENCE (FC)
  // ==========================================
  {
    id: "FC_SEARCHING_PAUSE_LONG",
    criterion: "FC",
    polarity: "ISSUE",
    labelVi: "Khựng lại tìm từ quá lâu (> 3 giây)",
    descriptionVi: "Khoảng lặng ngắt quãng kéo dài do bị kẹt từ vựng hoặc bế tắc ý tưởng.",
    inclusionRule: "Gắn khi có các khoảng im lặng chết (dead air) trên 3 giây làm đứt mạch bài nói.",
    exclusionRule: "Không gắn cho khoảng dừng ngắt nhịp thở tự nhiên theo cụm nghĩa (dưới 1-2 giây).",
    displayOrder: 9,
    version: "1.0",
  },
  {
    id: "FC_EXCESSIVE_SELF_CORRECTION",
    criterion: "FC",
    polarity: "ISSUE",
    labelVi: "Tự sửa câu liên tục làm đứt mạch",
    descriptionVi: "Nói vấp rồi lặp lại câu nhiều lần, liên tục đính chính làm người nghe mất tập trung.",
    inclusionRule: "Gắn khi thí sinh liên tục 'I mean...', 'sorry...' lặp lại nửa câu trước đó nhiều lần.",
    exclusionRule: "Không gắn nếu thí sinh chỉ tự sửa 1-2 lần trong toàn bộ bài nói một cách kín đáo.",
    displayOrder: 10,
    version: "1.0",
  },
  {
    id: "FC_TRUNCATED_IDEA",
    criterion: "FC",
    polarity: "ISSUE",
    labelVi: "Trả lời cụt ý / Chưa biết mở rộng",
    descriptionVi: "Câu trả lời quá ngắn (1-2 câu), dừng lại sớm, thiếu mở rộng bằng lý do hoặc ví dụ.",
    inclusionRule: "Gắn khi câu trả lời ở Part 1/Part 3 bị bỏ ngỏ, thiếu ý hỗ trợ khiến giám khảo phải hỏi thêm.",
    exclusionRule: "Không gắn nếu thí sinh trả lời ngắn nhưng súc tích và giám khảo chủ động chuyển câu hỏi.",
    displayOrder: 11,
    version: "1.0",
  },
  {
    id: "FC_DISCOURSE_FILLER_OVERUSE",
    criterion: "FC",
    polarity: "ISSUE",
    labelVi: "Lạm dụng từ chêm (Like, You know, Um)",
    descriptionVi: "Phát ra quá nhiều từ đệm vô nghĩa lặp đi lặp lại làm loãng nội dung câu nói.",
    inclusionRule: "Gắn khi các từ 'like, you know, actually, um, ah' xuất hiện với tần suất dày đặc trong mỗi câu.",
    exclusionRule: "Không gắn nếu từ chêm được sử dụng chừng mực để kéo dài thời gian suy nghĩ tự nhiên.",
    displayOrder: 12,
    version: "1.0",
  },
  {
    id: "FC_OVERUSED_MECHANICAL_LINKERS",
    criterion: "FC",
    polarity: "ISSUE",
    labelVi: "Dùng từ nối gượng như bài viết luận",
    descriptionVi: "Nhồi nhét các từ nối trang trọng của văn viết (Moreover, Furthermore) vào đàm thoại đời thường.",
    inclusionRule: "Gắn khi thí sinh dùng liên tiếp các từ nối cứng nhắc như đang đọc một bài tiểu luận Task 2.",
    exclusionRule: "Không gắn nếu từ nối được dùng đúng ngữ cảnh tranh biện học thuật ở Part 3.",
    displayOrder: 13,
    version: "1.0",
  },
  {
    id: "FC_CONTINUOUS_FLOW",
    criterion: "FC",
    polarity: "STRENGTH",
    labelVi: "Dòng nói liền mạch, tốc độ ổn định",
    descriptionVi: "Duy trì tốc độ nói vừa phải, trôi chảy, không có khoảng lặng ngập ngừng đáng kể.",
    inclusionRule: "Gắn khi bài nói có sự lưu loát tự nhiên, người nói tự tin dẫn dắt câu chuyện.",
    exclusionRule: "Không gắn nếu nói quá nhanh như học thuộc lòng (rushed delivery).",
    displayOrder: 14,
    version: "1.0",
  },
  {
    id: "FC_COHESIVE_IDEA_EXPANSION",
    criterion: "FC",
    polarity: "STRENGTH",
    labelVi: "Mở rộng ý có chiều sâu và ví dụ hay",
    descriptionVi: "Biết cách triển khai câu trả lời đầy đặn, có liên kết logic giữa nguyên nhân, kết quả và ví dụ.",
    inclusionRule: "Gắn khi câu trả lời có cấu trúc rõ ràng: Luận điểm -> Giải thích -> Ví dụ thực tế.",
    exclusionRule: "Không gắn nếu nói dài nhưng lan man lạc đề.",
    displayOrder: 15,
    version: "1.0",
  },
  {
    id: "FC_NATURAL_DISCOURSE_MARKERS",
    criterion: "FC",
    polarity: "STRENGTH",
    labelVi: "Dùng từ nối giao tiếp rất tự nhiên",
    descriptionVi: "Sử dụng linh hoạt các từ chuyển tiếp đàm thoại bản xứ như 'Well, Honestly, To be fair'.",
    inclusionRule: "Gắn khi các liên từ hội thoại xuất hiện tự nhiên, đúng ngữ điệu và ăn khớp với luồng suy nghĩ.",
    exclusionRule: "Không gắn nếu dùng từ nối một cách rập khuôn hoặc lặp lại một từ duy nhất.",
    displayOrder: 16,
    version: "1.0",
  },

  // ==========================================
  // 3. LEXICAL RESOURCE (LR)
  // ==========================================
  {
    id: "LR_LITERAL_TRANSLATION",
    criterion: "LR",
    polarity: "ISSUE",
    labelVi: "Dịch từng chữ từ tiếng Việt sang",
    descriptionVi: "Ghép từ theo cú pháp và tư duy tiếng mẹ đẻ, tạo thành các cụm từ kỳ quặc trong tiếng Anh.",
    inclusionRule: "Gắn khi cụm từ bắt nguồn trực tiếp từ nghĩa đen tiếng Việt (VD: 'open the light', 'eat soup', 'learn by heart').",
    exclusionRule: "Không gắn cho lỗi sai kết hợp từ thông thường của người học tiếng Anh nói chung (dùng LR_UNNATURAL_COLLOCATION).",
    displayOrder: 17,
    version: "1.0",
  },
  {
    id: "LR_UNNATURAL_COLLOCATION",
    criterion: "LR",
    polarity: "ISSUE",
    labelVi: "Ghép cụm từ chưa tự nhiên (Sai Collocation)",
    descriptionVi: "Dùng từ đúng nghĩa đơn lẻ nhưng sai quy ước kết hợp tự nhiên của người bản xứ.",
    inclusionRule: "Gắn khi thí sinh ghép từ sai (VD: 'make a research', 'do a choice', 'big rain').",
    exclusionRule: "Không gắn nếu cụm từ mang tính dịch thô từ tiếng Việt (dùng LR_LITERAL_TRANSLATION).",
    displayOrder: 18,
    version: "1.0",
  },
  {
    id: "LR_REPETITIVE_BASIC_WORDS",
    criterion: "LR",
    polarity: "ISSUE",
    labelVi: "Lặp lại các từ cơ bản (good, very, bad)",
    descriptionVi: "Hạn chế vốn từ, lặp đi lặp lại các tính từ/trạng từ cơ bản mà không có từ thay thế.",
    inclusionRule: "Gắn khi suốt bài nói thí sinh chỉ dùng các từ tiểu học quen thuộc mà không paraphrase được.",
    exclusionRule: "Không gắn nếu thí sinh dùng từ cơ bản nhưng kết hợp với phó từ phong phú.",
    displayOrder: 19,
    version: "1.0",
  },
  {
    id: "LR_FORCED_ACADEMIC_REGISTER",
    criterion: "LR",
    polarity: "ISSUE",
    labelVi: "Dùng từ đao to búa lớn sai ngữ cảnh",
    descriptionVi: "Cố nhồi nhét từ vựng C2/Academic quá trịnh trọng vào ngữ cảnh sinh hoạt thường ngày.",
    inclusionRule: "Gắn khi từ vựng học thuật bị dùng gượng ép trong Part 1 hoặc câu hỏi đời thường.",
    exclusionRule: "Không gắn nếu từ ngữ trang trọng được dùng đúng ngữ cảnh học thuật trong Part 3.",
    displayOrder: 20,
    version: "1.0",
  },
  {
    id: "LR_INCORRECT_WORD_FORM",
    criterion: "LR",
    polarity: "ISSUE",
    labelVi: "Dùng lộn dạng từ (Danh / Tính / Động)",
    descriptionVi: "Nhầm lẫn từ loại khi nói ở tốc độ nhanh (VD: dùng động từ thay cho danh từ).",
    inclusionRule: "Gắn khi thí sinh nói 'It is importance' (thay vì important), 'He is success' (thay vì successful).",
    exclusionRule: "Không gắn cho lỗi ngữ pháp về thì hay số nhiều (thuộc tiêu chí GRA).",
    displayOrder: 21,
    version: "1.0",
  },
  {
    id: "LR_NATURAL_IDIOMATIC_COLLOCATION",
    criterion: "LR",
    polarity: "STRENGTH",
    labelVi: "Cụm từ (Collocations) rất tự nhiên",
    descriptionVi: "Sử dụng các cụm từ kết hợp chuẩn xác, tự nhiên theo thói quen của người bản xứ.",
    inclusionRule: "Gắn khi bài nói xuất hiện các collocations đắt giá, tự nhiên (VD: 'bitterly cold', 'bear in mind').",
    exclusionRule: "Không gắn nếu cụm từ chỉ ở mức thông thường cơ bản (như 'have breakfast').",
    displayOrder: 22,
    version: "1.0",
  },
  {
    id: "LR_PRECISE_TOPIC_VOCABULARY",
    criterion: "LR",
    polarity: "STRENGTH",
    labelVi: "Từ vựng chuyên đề chuẩn xác, đắt giá",
    descriptionVi: "Sử dụng đúng thuật ngữ và từ vựng chuyên sâu của chủ đề (Môi trường, Công nghệ, Nghệ thuật).",
    inclusionRule: "Gắn khi thí sinh diễn đạt ý tưởng chuyên đề bằng vốn từ chính xác, tinh tế thay vì nói chung chung.",
    exclusionRule: "Không gắn nếu dùng từ chuyên đề nhưng phát âm sai hoàn toàn hoặc không hiểu nghĩa.",
    displayOrder: 23,
    version: "1.0",
  },
  {
    id: "LR_FLEXIBLE_PARAPHRASING",
    criterion: "LR",
    polarity: "STRENGTH",
    labelVi: "Biến đổi từ khóa (Paraphrase) khéo léo",
    descriptionVi: "Biết cách biến đổi câu hỏi của giám khảo bằng các từ đồng nghĩa hoặc cấu trúc khác linh hoạt.",
    inclusionRule: "Gắn khi mở đầu câu trả lời thí sinh paraphrase trôi chảy, không lặp lại nguyên văn lời giám khảo.",
    exclusionRule: "Không gắn nếu chỉ thay đổi 1 từ đơn giản mà ngữ pháp bị vỡ.",
    displayOrder: 24,
    version: "1.0",
  },

  // ==========================================
  // 4. GRAMMATICAL RANGE & ACCURACY (GRA)
  // ==========================================
  {
    id: "GRA_PAST_TENSE_DROP",
    criterion: "GRA",
    polarity: "ISSUE",
    labelVi: "Quên chia thì Quá khứ khi kể chuyện",
    descriptionVi: "Rớt về thì Hiện tại đơn khi đang kể lại một sự kiện đã kết thúc trong quá khứ ở Part 2.",
    inclusionRule: "Gắn khi bài nói Part 2 kể về trải nghiệm cũ nhưng động từ chia ở Hiện tại đơn.",
    exclusionRule: "Không gắn nếu thí sinh đang nói về cảm nhận ở thời điểm hiện tại đối với sự kiện đó.",
    displayOrder: 25,
    version: "1.0",
  },
  {
    id: "GRA_PRONOUN_HE_SHE_CONFUSION",
    criterion: "GRA",
    polarity: "ISSUE",
    labelVi: "Nói nhầm He / She / It",
    descriptionVi: "Nhầm lẫn đại từ nhân xưng khi phản xạ nhanh do ảnh hưởng của đại từ ngôi thứ 3 tiếng Việt.",
    inclusionRule: "Gắn khi kể về mẹ/chị nhưng nói 'he', hoặc kể về bố/anh nhưng nói 'she' lặp đi lặp lại.",
    exclusionRule: "Không gắn nếu chỉ nói nhầm 1 lần và lập tức tự sửa lại chuẩn xác.",
    displayOrder: 26,
    version: "1.0",
  },
  {
    id: "GRA_OVERRELIANCE_SIMPLE_SENTENCES",
    criterion: "GRA",
    polarity: "ISSUE",
    labelVi: "Lạm dụng câu đơn cụt, thiếu câu phức",
    descriptionVi: "Toàn bộ bài nói chỉ gồm các câu đơn ngắn ghép bằng 'and/but', thiếu mệnh đề phụ thuộc.",
    inclusionRule: "Gắn khi bài nói nghèo nàn về cấu trúc, không có mệnh đề quan hệ, điều kiện hoặc nhượng bộ.",
    exclusionRule: "Không gắn nếu thí sinh dùng câu ngắn có chủ đích để tạo hiệu ứng nhấn mạnh.",
    displayOrder: 27,
    version: "1.0",
  },
  {
    id: "GRA_MISSING_ARTICLES_PLURALS",
    criterion: "GRA",
    polarity: "ISSUE",
    labelVi: "Thiếu mạo từ (a/an/the) hoặc số nhiều",
    descriptionVi: "Bỏ quên mạo từ trước danh từ đếm được, hoặc không thêm đuôi số nhiều cho danh từ.",
    inclusionRule: "Gắn khi thí sinh nói 'I have cat', 'many student' một cách có hệ thống.",
    exclusionRule: "Không gắn nếu lỗi xuất phát từ phát âm nuốt âm gió đuôi (khi đó dùng PR_OMIT_FINAL_CONSONANT).",
    displayOrder: 28,
    version: "1.0",
  },
  {
    id: "GRA_SUBJECT_VERB_AGREEMENT",
    criterion: "GRA",
    polarity: "ISSUE",
    labelVi: "Sai hòa hợp Chủ ngữ - Động từ",
    descriptionVi: "Chủ ngữ số ít ngôi thứ ba nhưng động từ không chia số ít ở thì Hiện tại đơn.",
    inclusionRule: "Gắn khi thí sinh nói 'He go', 'She like', 'My friend want' trong bài nói.",
    exclusionRule: "Không gắn nếu thí sinh đang nói ở thì quá khứ (khi đó xem xét GRA_PAST_TENSE_DROP).",
    displayOrder: 29,
    version: "1.0",
  },
  {
    id: "GRA_COMPLEX_CLAUSE_MASTERY",
    criterion: "GRA",
    polarity: "STRENGTH",
    labelVi: "Sử dụng câu phức & mệnh đề rất khéo",
    descriptionVi: "Dùng nhuần nhuyễn câu điều kiện, mệnh đề quan hệ, câu nhượng bộ (Although, Even if).",
    inclusionRule: "Gắn khi bài nói có sự đan xen linh hoạt giữa câu đơn, câu ghép và các cấu trúc câu phức tự nhiên.",
    exclusionRule: "Không gắn nếu cố ghép câu quá dài dẫn đến mất kiểm soát cấu trúc và ngắt quãng.",
    displayOrder: 30,
    version: "1.0",
  },
  {
    id: "GRA_CONSISTENT_TENSE_CONTROL",
    criterion: "GRA",
    polarity: "STRENGTH",
    labelVi: "Giữ vững thì chuẩn xác suốt bài nói",
    descriptionVi: "Kiểm soát thời gian và các thì của động từ ổn định, chuyển đổi thì nhịp nhàng theo ngữ cảnh.",
    inclusionRule: "Gắn khi kể chuyện quá khứ hoặc dự báo tương lai với sự nhất quán tuyệt đối về thì động từ.",
    exclusionRule: "Không gắn nếu bài nói quá ngắn và chỉ dùng duy nhất thì Hiện tại đơn.",
    displayOrder: 31,
    version: "1.0",
  },
  {
    id: "GRA_HIGH_ACCURACY_DENSITY",
    criterion: "GRA",
    polarity: "STRENGTH",
    labelVi: "Độ chuẩn xác ngữ pháp cao, ít lỗi vặt",
    descriptionVi: "Mật độ câu hoàn toàn không có lỗi ngữ pháp áp đảo, thể hiện khả năng kiểm soát ngôn ngữ tự nhiên.",
    inclusionRule: "Gắn khi bài nói hầu như không mắc các lỗi ngữ pháp vặt về mạo từ, giới từ hay chia động từ.",
    exclusionRule: "Không gắn nếu thí sinh chỉ nói các câu quá đơn giản, an toàn để tránh lỗi.",
    displayOrder: 32,
    version: "1.0",
  },
];

async function seed() {
  console.log(`Starting seed for ${CANDIDATE_SPEAKING_TAGS.length} Speaking Evidence Tags...`);
  
  for (const tag of CANDIDATE_SPEAKING_TAGS) {
    await prisma.speakingEvidenceTag.upsert({
      where: { id: tag.id },
      update: {
        criterion: tag.criterion,
        polarity: tag.polarity,
        labelVi: tag.labelVi,
        descriptionVi: tag.descriptionVi,
        inclusionRule: tag.inclusionRule,
        exclusionRule: tag.exclusionRule,
        displayOrder: tag.displayOrder,
        version: tag.version,
        isActive: true,
      },
      create: {
        id: tag.id,
        criterion: tag.criterion,
        polarity: tag.polarity,
        labelVi: tag.labelVi,
        descriptionVi: tag.descriptionVi,
        inclusionRule: tag.inclusionRule,
        exclusionRule: tag.exclusionRule,
        displayOrder: tag.displayOrder,
        version: tag.version,
        isActive: true,
      },
    });
  }

  console.log("✅ Seed completed successfully for all 32 candidate speaking tags!");
}

seed()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
